name: learn-go-with-tests
root: <%= Dir.pwd %>

windows:
  - frontend:
      layout: main-vertical
      panes:
        - nvim
        - just watch-tests
        - just watch-checks
        - just watch-run
